# Vector

## Basic Operation

In [1]:
# import std libs
import math
import random
from functools import partial, reduce

In [2]:
def vector_add(v, w):
    """adds corresponding elements"""
    return [v_i + w_i
            for v_i, w_i in zip(v, w)]

def vector_subtract(v, w):
    """subtracts corresponding elements"""
    return [v_i - w_i
            for v_i, w_i in zip(v, w)]

In [3]:
# Three different implemenation of vector_sum

def vector_sum(vectors):
    """sums all corresponding elements"""
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_add(result, vector)
    return result

def vector_sum(vectors):
    return reduce(vector_add, vectors)

vector_sum = partial(reduce, vector_add)

In [4]:
def scalar_multiply(c, v):
    """c is a number, v is a vector"""
    return [c * v_i for v_i in v]

def vector_mean(vectors):
    """
    compute the vector whose ith element is the mean of the
    ith elements of the input vectors
    """
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

def dot(v, w):
    """v_1 * w_1 + ... + v_n * w_n"""
    return sum(v_i * w_i
               for v_i, w_i in zip(v, w))

def sum_of_squares(v):
    """v_1 * v_1 + ... + v_n * v_n"""
    return dot(v, v)

In [5]:
def magnitude(v):
    return math.sqrt(sum_of_squares(v))

def distance(v, w):
    return magnitude(vector_subtract(v, w))

### Example

In [6]:
random.seed(0)
v1 = [random.randint(1, 100) for _ in range(10)]
v2 = [random.randint(1, 100) for _ in range(10)]

In [7]:
v1

[50, 98, 54, 6, 34, 66, 63, 52, 39, 62]

In [8]:
v2

[46, 75, 28, 65, 18, 37, 18, 97, 13, 80]

In [9]:
vector_add(v1, v2)

[96, 173, 82, 71, 52, 103, 81, 149, 52, 142]

In [10]:
vector_subtract(v1, v2)

[4, 23, 26, -59, 16, 29, 45, -45, 26, -18]

In [11]:
vector_sum([v1, v2])

[96, 173, 82, 71, 52, 103, 81, 149, 52, 142]

In [12]:
scalar_multiply(5, v1)

[250, 490, 270, 30, 170, 330, 315, 260, 195, 310]

In [13]:
vector_mean([v1, v2])

[48.0, 86.5, 41.0, 35.5, 26.0, 51.5, 40.5, 74.5, 26.0, 71.0]

In [14]:
dot(v1, v2)

26251

In [15]:
sum_of_squares(v1)

32606

In [16]:
magnitude(v1)

180.5713155515017

In [17]:
distance(v1, v2)

104.1585330157832

### Further Exploration (numpy)

In [18]:
import numpy as np

np.random.seed(0)
v1 = np.random.randint(1, 100, size=10)
v2 = np.random.randint(1, 100, size=10)

In [19]:
v1

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [20]:
v2

array([71, 89, 89, 13, 59, 66, 40, 88, 47, 89])

In [21]:
v1 + v2
np.add(v1, v2)

array([116, 137, 154,  81, 127,  76, 124, 110,  84, 177])

In [22]:
v1 - v2
np.subtract(v1, v2)

array([-26, -41, -24,  55,   9, -56,  44, -66, -10,  -1])

In [23]:
# axis: 0 row, 1 column
np.sum([v1, v2], axis=0)

array([116, 137, 154,  81, 127,  76, 124, 110,  84, 177])

In [24]:
5 * v1

array([225, 240, 325, 340, 340,  50, 420, 110, 185, 440])

In [25]:
np.mean(v1)

53.5

In [26]:
v1.dot(v2)

33675

In [27]:
np.sum(np.square(v1))

34555

In [28]:
np.linalg.norm(v1)

185.88975227268446

In [29]:
np.linalg.norm(v1-v2)

124.77179168385777

---

# Matrices

## Basic Operation

In [30]:
def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0
    return num_rows, num_cols

def get_row(A, i):
    return A[i] # A[i] is already the ith row

def get_column(A, j):
    return [A_i[j] # jth element of row A_i
            for A_i in A] # for each row A_i

In [31]:
def make_matrix(num_rows, num_cols, entry_fn):
    """returns a num_rows x num_cols matrix
    whose (i,j)th entry is entry_fn(i, j)"""
    return [[entry_fn(i, j) # given i, create a list
             for j in range(num_cols)] # [entry_fn(i, 0), ... ]
            for i in range(num_rows)] # create one list for each i

## Examples

In [32]:
m1 = [[1, 2, 3], [4, 5, 6]]

In [33]:
m1

[[1, 2, 3], [4, 5, 6]]

In [34]:
shape(m1)

(2, 3)

In [35]:
get_row(m1, 1)

[4, 5, 6]

In [36]:
get_column(m1, 2)

[3, 6]

In [37]:
make_matrix(5, 10, lambda x, y: x+y)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]

### Further Exploration (numpy)

In [38]:
import numpy as np

In [39]:
m1 = np.matrix([[1, 2, 3] ,[4, 5, 6]])

In [40]:
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [41]:
m1.shape

(2, 3)

In [42]:
m1[1]

matrix([[4, 5, 6]])

In [43]:
m1[:, 2]

matrix([[3],
        [6]])

In [44]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [45]:
np.zeros((3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])